/**
 * updateDescriptions.mjs
 * Overwrites the `descripcion` field for specific tours in BdTours_es.json,
 * BdTours_en.json and BdTours_ja.json.
 * Run once:  node backend/scripts/updateDescriptions.mjs
 */

import { readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const JSON_DIR = path.join(__dirname, '..', '..', 'JSON');

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────
function load(file) {
  return JSON.parse(readFileSync(path.join(JSON_DIR, file), 'utf-8'));
}
function save(file, data) {
  writeFileSync(path.join(JSON_DIR, file), JSON.stringify(data, null, 4), 'utf-8');
}
function patch(tours, updates) {
  for (const tour of tours) {
    if (updates[tour.id]) {
      tour.descripcion = updates[tour.id];
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// ESPAÑOL
// ─────────────────────────────────────────────────────────────────────────────
const ES = {
  'tour-kyoto-8h':
    'Descubre tres de los lugares más emblemáticos y visitados de Kioto en un recorrido diseñado para quienes desean conocer la esencia de la antigua capital japonesa. Esta experiencia reúne algunos de los monumentos más representativos del país, combinando historia, espiritualidad y paisajes inolvidables.<br><br>Comenzaremos visitando el impresionante Templo Kinkakuji, conocido como el Pabellón Dorado y declarado Patrimonio de la Humanidad por la UNESCO. Cubierto de pan de oro y rodeado de jardines tradicionales y estanques, es uno de los símbolos más reconocidos de Japón.<br><br>Continuaremos hacia el famoso Santuario Fushimi Inari Taisha, célebre por sus miles de puertas torii de color rojo que se extienden a lo largo de la montaña. Este lugar sagrado ofrece una de las imágenes más icónicas de Japón y una experiencia única cargada de historia y tradición.<br><br>Finalizaremos nuestro recorrido en el majestuoso Templo Kiyomizudera, también declarado Patrimonio de la Humanidad por la UNESCO. Su espectacular terraza de madera, construida sin el uso de clavos, ofrece magníficas vistas de Kioto y constituye uno de los tesoros culturales más importantes del país.<br><br>Una experiencia perfecta para quienes visitan Kioto por primera vez y desean descubrir algunos de los lugares más famosos, bellos e históricos de Japón en un solo recorrido.',

  'tour-kyoto-3h':
    'Descubre el lado más tradicional y pintoresco de Kioto en un recorrido por algunos de sus barrios y templos más emblemáticos.<br><br>Comenzaremos caminando junto al tranquilo río Kamogawa, uno de los lugares favoritos de los habitantes de la ciudad para relajarse y disfrutar de la atmósfera única de Kioto. Continuaremos hacia Gion Shirakawa, una de las zonas más bellas y fotogénicas de la antigua capital. Sus calles adoquinadas, casas tradicionales de madera y canales bordeados de sauces conservan el encanto del Japón de otra época y representan la esencia del histórico distrito de las geishas.<br><br>Después visitaremos el impresionante Templo Chionin, sede principal de una de las escuelas budistas más importantes de Japón. Su imponente puerta de entrada y sus extensos terrenos ofrecen una experiencia de gran valor cultural y espiritual.<br><br>Seguiremos nuestro recorrido a través del Parque Maruyama, uno de los espacios verdes más famosos de Kioto, conocido por su ambiente tranquilo y sus hermosos paisajes durante todas las estaciones del año.<br><br>Finalmente llegaremos al majestuoso Templo Kiyomizudera, declarado Patrimonio de la Humanidad por la UNESCO y considerado uno de los monumentos más emblemáticos de Japón. Su famosa terraza de madera ofrece espectaculares vistas de la ciudad y constituye el cierre perfecto para una experiencia llena de historia, cultura y tradición.<br><br>Una experiencia ideal para quienes desean descubrir la belleza clásica de Kioto y sumergirse en la atmósfera única de la antigua capital japonesa.',

  'tour-himeji-3h':
    'Descubre la belleza y la historia de una de las ciudades más emblemáticas de Japón en este recorrido por Himeji.<br><br>Comenzaremos en la Estación de Himeji y recorreremos la elegante Calle Otemae, la avenida principal que conduce hacia el famoso castillo, disfrutando de las vistas de la ciudad y de su ambiente local. Durante el camino pasaremos por la tradicional Calle Yamasa Kamaboko, conocida por su conexión con uno de los productos gastronómicos más representativos de la región.<br><br>También visitaremos el histórico Santuario Harima Sosha, un importante lugar de culto con siglos de historia que refleja la profunda tradición espiritual de la zona.<br><br>El punto culminante del recorrido será el impresionante Castillo de Himeji, declarado Patrimonio de la Humanidad por la UNESCO y considerado el castillo feudal mejor conservado de Japón. Conocido como el "Castillo de la Garza Blanca" por su elegante apariencia, es uno de los monumentos históricos más importantes del país.<br><br>Finalizaremos visitando el Santuario Himeji, donde podrás disfrutar de una atmósfera tranquila y conocer más sobre las tradiciones y creencias locales.<br><br>Un recorrido ideal para quienes desean conocer la esencia histórica de Himeji, combinando cultura, arquitectura y patrimonio japonés en una experiencia inolvidable. 🏯✨',

  'tour-nara-3h':
    'Descubre la antigua capital de Japón en un recorrido lleno de historia, cultura y tradiciones.<br><br>Comenzaremos en la Estación Kintetsu Nara, punto de partida ideal para explorar una de las ciudades más históricas del país. Pasearemos junto al tranquilo Estanque Sarusawa-ike, uno de los paisajes más representativos de Nara, rodeado de historia y belleza natural.<br><br>Continuaremos hacia Kōfuku-ji, uno de los templos budistas más importantes de Japón, famoso por su elegante pagoda de cinco pisos, símbolo de la ciudad. Visitaremos el Museo Nacional de Nara, donde conoceremos más sobre el arte y el patrimonio cultural japonés, antes de dirigirnos al espectacular Templo Tōdai-ji, declarado Patrimonio de la Humanidad por la UNESCO. Este impresionante complejo alberga el Gran Buda de Nara, una de las estatuas de bronce más grandes del mundo y uno de los tesoros culturales más importantes de Japón.<br><br>A lo largo del recorrido también tendrás la oportunidad de disfrutar de la atmósfera única del Parque de Nara, hogar de los famosos ciervos considerados mensajeros sagrados en la tradición local.<br><br>Una experiencia ideal para quienes desean descubrir la riqueza histórica, espiritual y cultural de una de las ciudades más fascinantes de Japón. 🦌⛩️✨',

  'tour-nara-uji-8h':
    'Descubre dos de los destinos culturales más fascinantes de Japón en un recorrido que combina historia, espiritualidad y gastronomía tradicional.<br><br>Comenzaremos en Uji, una ciudad famosa por producir algunos de los mejores tés matcha del país. Visitaremos el impresionante Pabellón del Fénix del Byōdō-in, declarado Patrimonio de la Humanidad por la UNESCO y considerado una de las obras maestras de la arquitectura japonesa. Después pasearemos por la encantadora calle comercial de Uji, repleta de tiendas especializadas en matcha, dulces tradicionales y productos locales que reflejan la rica cultura del té de la región.<br><br>Continuaremos hacia Nara, la primera capital permanente de Japón. Allí recorreremos el pintoresco estanque Sarusawa-ike y visitaremos Kōfuku-ji, un importante templo budista declarado Patrimonio de la Humanidad por la UNESCO y reconocido por su histórica pagoda de cinco pisos.<br><br>También disfrutaremos de un paseo por el famoso Parque de Nara, hogar de los emblemáticos ciervos que conviven libremente con los visitantes y forman parte de la identidad de la ciudad.<br><br>El recorrido culminará en el majestuoso Templo Tōdai-ji, Patrimonio de la Humanidad por la UNESCO, donde se encuentra el Gran Buda de Nara, una de las estatuas de bronce más impresionantes y representativas de Japón.<br><br>Una experiencia perfecta para quienes desean conocer la esencia cultural de Japón a través de sus templos históricos, sus tradiciones centenarias y el auténtico sabor del matcha de Uji. 🍵🦌⛩️✨',

  'tour-himeji-kobe-8h':
    'Disfruta de un recorrido que combina dos de los destinos más fascinantes de la región de Kansai.<br><br>Comenzaremos visitando el majestuoso Castillo de Himeji, declarado Patrimonio de la Humanidad por la UNESCO y considerado el castillo feudal mejor conservado de Japón. Conocido como el "Castillo de la Garza Blanca", es una obra maestra de la arquitectura japonesa y uno de los monumentos históricos más impresionantes del país.<br><br>Tras explorar Himeji, viajaremos a Kobe Sannomiya, el corazón de una ciudad famosa por su ambiente cosmopolita y su historia internacional. Pasearemos por el moderno Parque Meriken, situado junto al puerto de Kobe, donde disfrutaremos de hermosas vistas al mar y de algunos de los símbolos más representativos de la ciudad.<br><br>A la hora del almuerzo, tendremos la oportunidad de degustar la reconocida carne de Kobe en Steakland, uno de los restaurantes más populares para probar esta famosa especialidad japonesa.<br><br>Por la tarde exploraremos el encantador distrito de Kitano, conocido por sus elegantes residencias de estilo occidental construidas por antiguos comerciantes y diplomáticos extranjeros. Finalizaremos el recorrido en Motomachi, una vibrante zona llena de historia, tiendas locales y una atmósfera que refleja la mezcla única entre Japón y las influencias internacionales que han dado forma a Kobe.<br><br>Una experiencia perfecta para quienes desean combinar patrimonio histórico, paisajes costeros, cultura internacional y una de las gastronomías más famosas de Japón en un solo día. 🏯⚓🥩✨',

  'tour-osaka-presentation':
    'Descubre la energía única de Osaka, una ciudad famosa por su vibrante vida urbana, su deliciosa gastronomía y su ambiente acogedor.<br><br>Comenzaremos nuestro recorrido en Shinsaibashi, una de las zonas comerciales más populares de la ciudad, donde se mezclan las últimas tendencias con la cultura local. Continuaremos hacia America Mura (Amerikamura), el corazón de la cultura juvenil de Osaka, conocido por su ambiente creativo, arte urbano, boutiques independientes y espíritu alternativo que lo convierten en uno de los barrios más dinámicos de Japón.<br><br>Después llegaremos a Dotonbori, el distrito más emblemático de Osaka, famoso por sus enormes carteles luminosos, sus animadas calles y la inconfundible atmósfera que ha convertido a esta zona en uno de los lugares más fotografiados del país.<br><br>A pocos pasos visitaremos el histórico Templo Hozenji, un rincón de tranquilidad que conserva el encanto del Osaka tradicional y ofrece un contraste fascinante con el bullicio de las calles cercanas.<br><br>Finalizaremos nuestra experiencia en el famoso Mercado Kuromon, conocido como la "Cocina de Osaka", donde podrás descubrir productos locales, mariscos frescos, dulces japoneses y algunas de las especialidades gastronómicas más representativas de la ciudad.<br><br>Una experiencia perfecta para quienes desean conocer la esencia de Osaka a través de su cultura, su gastronomía y su vibrante vida urbana. 🍜✨🏮🇯🇵',

  'tour-osaka-3h':
    'Descubre la energía vibrante de Osaka en un recorrido que combina modernidad, tradición y algunos de los lugares más emblemáticos de la ciudad.<br><br>Comenzaremos en Shinsaibashi, una de las zonas comerciales más populares de Osaka, donde las calles llenas de tiendas, cafeterías y vida urbana muestran el lado más dinámico de la ciudad.<br><br>Continuaremos hacia America Mura, el corazón de la cultura juvenil de Osaka. Con sus murales, tiendas alternativas y ambiente creativo, este barrio refleja el espíritu moderno y desenfadado que caracteriza a la ciudad.<br><br>Después nos dirigiremos a Dotonbori, el distrito más famoso de Osaka, conocido por sus espectaculares letreros luminosos, su animada atmósfera y su papel como símbolo de la vida nocturna y gastronómica local. Aquí podrás disfrutar de algunas de las vistas más icónicas de Japón.<br><br>A pocos pasos visitaremos el tradicional Templo Hozenji, un pequeño oasis de tranquilidad que conserva el encanto del Osaka histórico y ofrece un interesante contraste con el bullicio de las calles cercanas.<br><br>Finalizaremos nuestro recorrido en el Mercado Kuromon, conocido como la "Cocina de Osaka". Este mercado histórico alberga una gran variedad de productos frescos, especialidades locales y algunos de los sabores más representativos de la gastronomía japonesa.<br><br>Una experiencia ideal para quienes desean conocer la esencia de Osaka a través de su cultura urbana, sus tradiciones y su reconocida escena gastronómica.',

  'tour-osaka-8h':
    'Descubre algunos de los lugares más emblemáticos de Osaka en un recorrido que combina historia, cultura y la energía única de una de las ciudades más vibrantes de Japón.<br><br>Comenzaremos visitando el majestuoso Castillo de Osaka, uno de los monumentos históricos más importantes del país y símbolo de la ciudad. Rodeado de extensos jardines y murallas centenarias, este castillo ofrece una fascinante introducción a la historia del Japón feudal.<br><br>Continuaremos hacia el animado distrito de Namba, el corazón del entretenimiento y la vida urbana de Osaka. Sus calles llenas de actividad, comercios y restaurantes reflejan el carácter dinámico y acogedor por el que la ciudad es conocida.<br><br>Después exploraremos la fascinante zona de Shinsekai, un barrio lleno de nostalgia que conserva la atmósfera del Osaka de principios del siglo XX. Sus coloridos letreros, calles tradicionales y ambiente local ofrecen una experiencia diferente y auténtica.<br><br>Además, el recorrido incluye los puntos más destacados de nuestro tour a pie por Osaka, permitiendo descubrir lugares emblemáticos, rincones históricos y algunas de las zonas más representativas de la ciudad.<br><br>Una experiencia ideal para quienes desean conocer la esencia de Osaka a través de su historia, su cultura y su inconfundible energía urbana.',

  'tour-kobe-3h':
    'Descubre el encanto único de Kobe, una ciudad donde la tradición japonesa y la influencia internacional se combinan de manera excepcional.<br><br>Comenzaremos nuestro recorrido en Sannomiya, el corazón de la ciudad y punto de encuentro perfecto para explorar algunos de sus lugares más emblemáticos.<br><br>Nuestra primera parada será Ikuta Jinja, uno de los santuarios más antiguos de Japón, con más de 1.800 años de historia. Rodeado de naturaleza en pleno centro urbano, este santuario ofrece una introducción perfecta a las tradiciones espirituales de la ciudad.<br><br>Continuaremos hacia el famoso Starbucks Kitano Ijinkan, ubicado en una histórica residencia occidental que refleja el pasado internacional de Kobe. Este edificio, considerado uno de los Starbucks más bellos de Japón, permite apreciar la arquitectura que caracteriza al distrito de Kitano.<br><br>Seguiremos explorando esta elegante zona hasta llegar a la emblemática Casa Weathercock (Kazamidori no Yakata), uno de los símbolos más reconocidos de Kobe. Su distintiva arquitectura y su historia ofrecen una mirada fascinante a la época en que comerciantes y diplomáticos extranjeros se establecieron en la ciudad.<br><br>Durante el recorrido también pasaremos por Steakland, uno de los restaurantes más populares para degustar la mundialmente famosa carne de Kobe, una de las especialidades gastronómicas más prestigiosas de Japón.<br><br>Una experiencia perfecta para quienes desean descubrir la historia, la cultura y la atmósfera cosmopolita que han convertido a Kobe en una de las ciudades más fascinantes del país.',

  'tour-kobe-8h':
    'Descubre la esencia de Kobe en un recorrido que combina historia, arquitectura internacional, naturaleza y espectaculares vistas al mar.<br><br>Comenzaremos en Sannomiya, el corazón de la ciudad y punto de partida ideal para explorar algunos de sus lugares más emblemáticos.<br><br>Nuestra primera parada será el Santuario Ikuta, uno de los santuarios más antiguos de Japón, con una historia que se remonta a más de 1.800 años. Este tranquilo espacio ofrece una fascinante introducción a las tradiciones y creencias japonesas.<br><br>Continuaremos hacia el encantador distrito de Kitano Ijinkan, famoso por sus elegantes residencias de estilo occidental construidas por comerciantes y diplomáticos extranjeros durante la apertura internacional de Kobe. Sus calles llenas de historia y arquitectura única reflejan el carácter cosmopolita que distingue a la ciudad.<br><br>Después visitaremos las impresionantes Cascadas Nunobiki, un rincón natural situado a poca distancia del centro urbano que ofrece paisajes tranquilos y una experiencia diferente dentro de la ciudad.<br><br>Durante el recorrido también pasaremos por Steakland, uno de los lugares más populares para degustar la mundialmente famosa carne de Kobe, una de las especialidades gastronómicas más reconocidas de Japón.<br><br>Por la tarde nos dirigiremos al moderno Parque Meriken, ubicado junto al puerto de Kobe. Desde aquí disfrutaremos de hermosas vistas de la bahía, los espacios abiertos frente al mar y algunos de los símbolos más representativos de la ciudad.<br><br>Finalizaremos junto a la icónica Torre del Puerto de Kobe, uno de los monumentos más reconocibles de la ciudad y un excelente lugar para admirar el paisaje urbano y marítimo que han convertido a Kobe en una de las ciudades portuarias más importantes de Japón.<br><br>Una experiencia perfecta para quienes desean descubrir la combinación única de historia, naturaleza, cultura internacional y paisajes costeros que hacen de Kobe un destino inolvidable.',
};

// ─────────────────────────────────────────────────────────────────────────────
// ENGLISH
// ─────────────────────────────────────────────────────────────────────────────
const EN = {
  'tour-kyoto-8h':
    'Discover three of Kyoto\'s most iconic and visited landmarks on a tour designed for those who wish to know the essence of Japan\'s ancient capital. This experience brings together some of the country\'s most representative monuments, combining history, spirituality, and unforgettable scenery.<br><br>We will begin by visiting the stunning Kinkakuji Temple, known as the Golden Pavilion and designated a UNESCO World Heritage Site. Covered in gold leaf and surrounded by traditional gardens and ponds, it is one of the most recognized symbols of Japan.<br><br>We will then continue to the famous Fushimi Inari Taisha Shrine, renowned for its thousands of vermilion torii gates that wind their way up the mountain. This sacred place offers one of Japan\'s most iconic images and a unique experience steeped in history and tradition.<br><br>We will conclude our tour at the majestic Kiyomizudera Temple, also a UNESCO World Heritage Site. Its spectacular wooden terrace, built without the use of nails, offers magnificent views of Kyoto and stands as one of the country\'s most important cultural treasures.<br><br>A perfect experience for those visiting Kyoto for the first time who wish to discover some of Japan\'s most famous, beautiful, and historic places all in one tour.',

  'tour-kyoto-3h':
    'Discover the most traditional and picturesque side of Kyoto on a tour through some of its most iconic neighborhoods and temples.<br><br>We will begin with a walk along the tranquil Kamogawa River, one of the city\'s favorite spots for locals to relax and enjoy Kyoto\'s unique atmosphere. We will then head to Gion Shirakawa, one of the most beautiful and photogenic areas of the ancient capital. Its cobblestone streets, traditional wooden townhouses, and willow-lined canals preserve the charm of old Japan and embody the essence of the historic geisha district.<br><br>Next, we will visit the impressive Chionin Temple, the head temple of one of Japan\'s most important Buddhist schools. Its imposing main gate and expansive grounds offer an experience of great cultural and spiritual value.<br><br>We will continue through Maruyama Park, one of Kyoto\'s most famous green spaces, known for its tranquil atmosphere and beautiful scenery throughout all seasons.<br><br>Finally, we will arrive at the majestic Kiyomizudera Temple, a UNESCO World Heritage Site and one of Japan\'s most iconic monuments. Its famous wooden terrace offers spectacular views of the city and provides the perfect conclusion to an experience filled with history, culture, and tradition.<br><br>An ideal experience for those who wish to discover the classic beauty of Kyoto and immerse themselves in the unique atmosphere of Japan\'s ancient capital.',

  'tour-himeji-3h':
    'Discover the beauty and history of one of Japan\'s most iconic cities on this tour of Himeji.<br><br>We will begin at Himeji Station and stroll along the elegant Otemae Street, the main avenue leading to the famous castle, taking in the city views and local atmosphere. Along the way, we will pass by the traditional Yamasa Kamaboko Street, known for its connection to one of the region\'s most emblematic culinary products.<br><br>We will also visit the historic Harima Sosha Shrine, an important place of worship with centuries of history that reflects the deep spiritual tradition of the area.<br><br>The highlight of the tour will be the breathtaking Himeji Castle, a UNESCO World Heritage Site and considered the best-preserved feudal castle in Japan. Known as the "White Heron Castle" for its elegant appearance, it is one of the country\'s most important historic monuments.<br><br>We will conclude with a visit to Himeji Shrine, where you can enjoy a peaceful atmosphere and learn more about local traditions and beliefs.<br><br>An ideal tour for those who wish to discover the historical essence of Himeji, combining culture, architecture, and Japanese heritage in an unforgettable experience. 🏯✨',

  'tour-nara-3h':
    'Discover Japan\'s ancient capital on a tour filled with history, culture, and traditions.<br><br>We will begin at Kintetsu Nara Station, the ideal starting point for exploring one of the country\'s most historic cities. We will stroll alongside the tranquil Sarusawa-ike Pond, one of Nara\'s most representative landscapes, surrounded by history and natural beauty.<br><br>We will then head to Kōfuku-ji, one of Japan\'s most important Buddhist temples, famous for its elegant five-story pagoda, the symbol of the city. We will visit the Nara National Museum to learn more about Japanese art and cultural heritage, before making our way to the spectacular Tōdai-ji Temple, a UNESCO World Heritage Site. This impressive complex houses the Great Buddha of Nara, one of the largest bronze statues in the world and one of Japan\'s most important cultural treasures.<br><br>Throughout the tour you will also have the opportunity to enjoy the unique atmosphere of Nara Park, home to the famous deer regarded as sacred messengers in local tradition.<br><br>An ideal experience for those who wish to discover the rich historical, spiritual, and cultural wealth of one of Japan\'s most fascinating cities. 🦌⛩️✨',

  'tour-nara-uji-8h':
    'Discover two of Japan\'s most fascinating cultural destinations on a tour that combines history, spirituality, and traditional gastronomy.<br><br>We will begin in Uji, a city famous for producing some of the finest matcha tea in the country. We will visit the stunning Phoenix Pavilion of Byōdō-in, a UNESCO World Heritage Site considered one of the masterpieces of Japanese architecture. We will then stroll along Uji\'s charming shopping street, lined with specialty matcha shops, traditional sweets, and local products that reflect the rich tea culture of the region.<br><br>We will continue to Nara, Japan\'s first permanent capital. There we will walk alongside the picturesque Sarusawa-ike pond and visit Kōfuku-ji, an important Buddhist temple and UNESCO World Heritage Site known for its historic five-story pagoda.<br><br>We will also enjoy a stroll through the famous Nara Park, home to the iconic deer that roam freely among visitors and form part of the city\'s identity.<br><br>The tour will culminate at the majestic Tōdai-ji Temple, a UNESCO World Heritage Site where the Great Buddha of Nara stands as one of the most impressive and iconic bronze statues in Japan.<br><br>A perfect experience for those who wish to discover the cultural essence of Japan through its historic temples, centuries-old traditions, and the authentic flavor of Uji matcha. 🍵🦌⛩️✨',

  'tour-himeji-kobe-8h':
    'Enjoy a tour that combines two of the most fascinating destinations in the Kansai region.<br><br>We will begin by visiting the majestic Himeji Castle, a UNESCO World Heritage Site and considered the best-preserved feudal castle in Japan. Known as the "White Heron Castle," it is a masterpiece of Japanese architecture and one of the country\'s most impressive historical monuments.<br><br>After exploring Himeji, we will travel to Kobe Sannomiya, the heart of a city famous for its cosmopolitan atmosphere and international history. We will stroll through the modern Meriken Park, located beside Kobe\'s harbor, enjoying beautiful sea views and some of the city\'s most representative landmarks.<br><br>At lunchtime, we will have the opportunity to savor the renowned Kobe beef at Steakland, one of the most popular restaurants for this famous Japanese specialty.<br><br>In the afternoon we will explore the charming Kitano district, known for its elegant Western-style residences built by former foreign merchants and diplomats. We will conclude at Motomachi, a vibrant area full of history, local shops, and an atmosphere that reflects the unique blend of Japan and the international influences that have shaped Kobe.<br><br>A perfect experience for those who wish to combine historic heritage, coastal scenery, international culture, and one of Japan\'s most celebrated cuisines all in a single day. 🏯⚓🥩✨',

  'tour-osaka-3h':
    'Discover the vibrant energy of Osaka on a tour that combines modernity, tradition, and some of the city\'s most emblematic places.<br><br>We will begin at Shinsaibashi, one of Osaka\'s most popular shopping areas, where streets filled with stores, cafés, and urban life showcase the city\'s most dynamic side.<br><br>We will then head to America Mura, the heart of Osaka\'s youth culture. With its murals, alternative shops, and creative atmosphere, this neighborhood reflects the modern and carefree spirit that defines the city.<br><br>Next we will make our way to Dotonbori, Osaka\'s most famous district, known for its spectacular illuminated signs, lively atmosphere, and its role as a symbol of the city\'s nightlife and gastronomic scene. Here you can enjoy some of Japan\'s most iconic views.<br><br>Just steps away, we will visit the traditional Hozenji Temple, a small oasis of tranquility that preserves the charm of historic Osaka and offers an interesting contrast with the busy streets nearby.<br><br>We will conclude our tour at Kuromon Market, known as "Osaka\'s Kitchen." This historic market houses a wide variety of fresh produce, local specialties, and some of the most representative flavors of Japanese cuisine.<br><br>An ideal experience for those who wish to discover the essence of Osaka through its urban culture, traditions, and renowned gastronomic scene.',

  'tour-osaka-8h':
    'Discover some of Osaka\'s most iconic landmarks on a tour that combines history, culture, and the unique energy of one of Japan\'s most vibrant cities.<br><br>We will begin by visiting the majestic Osaka Castle, one of the country\'s most important historical monuments and a symbol of the city. Surrounded by expansive gardens and centuries-old walls, this castle offers a fascinating introduction to the history of feudal Japan.<br><br>We will then head to the lively Namba district, the heart of Osaka\'s entertainment and urban life. Its bustling streets filled with shops and restaurants reflect the dynamic and welcoming character for which the city is known.<br><br>Afterward we will explore the fascinating Shinsekai area, a neighborhood steeped in nostalgia that preserves the atmosphere of early-20th-century Osaka. Its colorful signs, traditional streets, and local ambiance offer a different and authentic experience.<br><br>The tour also includes the highlights of our Osaka walking tour, allowing us to discover iconic landmarks, historic corners, and some of the city\'s most representative areas.<br><br>An ideal experience for those who wish to discover the essence of Osaka through its history, culture, and unmistakable urban energy.',

  'tour-kobe-3h':
    'Discover the unique charm of Kobe, a city where Japanese tradition and international influence come together in an exceptional way.<br><br>We will begin our tour in Sannomiya, the heart of the city and the perfect meeting point to explore some of its most iconic places.<br><br>Our first stop will be Ikuta Jinja, one of Japan\'s oldest shrines, with over 1,800 years of history. Surrounded by nature in the very center of the city, this shrine offers a perfect introduction to Kobe\'s spiritual traditions.<br><br>We will then head to the famous Starbucks Kitano Ijinkan, housed in a historic Western-style residence that reflects Kobe\'s international past. This building, considered one of the most beautiful Starbucks in Japan, allows visitors to appreciate the architecture that characterizes the Kitano district.<br><br>We will continue exploring this elegant area until we reach the iconic Weathercock House (Kazamidori no Yakata), one of Kobe\'s most recognized symbols. Its distinctive architecture and history offer a fascinating glimpse into the era when foreign merchants and diplomats settled in the city.<br><br>During the tour we will also pass by Steakland, one of the most popular restaurants for tasting the world-famous Kobe beef, one of Japan\'s most prestigious culinary specialties.<br><br>A perfect experience for those who wish to discover the history, culture, and cosmopolitan atmosphere that have made Kobe one of the most fascinating cities in the country.',

  'tour-kobe-8h':
    'Discover the essence of Kobe on a tour that combines history, international architecture, nature, and spectacular sea views.<br><br>We will begin in Sannomiya, the heart of the city and the ideal starting point for exploring some of its most iconic landmarks.<br><br>Our first stop will be the Ikuta Shrine, one of Japan\'s oldest shrines, with a history spanning more than 1,800 years. This peaceful space offers a fascinating introduction to Japanese traditions and beliefs.<br><br>We will then head to the charming Kitano Ijinkan district, famous for its elegant Western-style residences built by foreign merchants and diplomats during Kobe\'s international opening. Its history-filled streets and unique architecture reflect the cosmopolitan character that distinguishes the city.<br><br>Next we will visit the impressive Nunobiki Falls, a natural gem located a short distance from the city center that offers tranquil scenery and a different kind of experience within the city.<br><br>During the tour we will also pass by Steakland, one of the most popular spots for tasting the world-famous Kobe beef, one of Japan\'s most celebrated culinary specialties.<br><br>In the afternoon we will head to the modern Meriken Park, located beside Kobe\'s port. From here we will enjoy beautiful views of the bay, the open waterfront spaces, and some of the city\'s most representative landmarks.<br><br>We will conclude at the iconic Kobe Port Tower, one of the city\'s most recognizable monuments and an excellent spot to admire the urban and maritime landscape that have made Kobe one of Japan\'s most important port cities.<br><br>A perfect experience for those who wish to discover the unique combination of history, nature, international culture, and coastal scenery that make Kobe an unforgettable destination.',
};

// ─────────────────────────────────────────────────────────────────────────────
// 日本語
// ─────────────────────────────────────────────────────────────────────────────
const JA = {
  'tour-kyoto-8h':
    '日本の古都・京都の最も象徴的で訪問者の多い3つの名所を巡るツアーで、古都の真髄を知りたい方のために設計されています。歴史、精神性、そして忘れられない景色が融合した、日本を代表するモニュメントを巡る特別な体験です。<br><br>最初に訪れるのは、黄金閣として知られる金閣寺。ユネスコ世界遺産に登録されたこの寺院は、金箔で覆われた美しい姿が伝統的な庭園の池に映り込み、日本を代表するシンボルの一つです。<br><br>次に向かうのは、朱色の鳥居が山道に連なることで有名な伏見稲荷大社。この神聖な場所は日本で最も印象的な風景の一つを提供しており、歴史と伝統に満ちたかけがえない体験ができます。<br><br>最後はユネスコ世界遺産にも登録された壮大な清水寺。釘を一本も使わずに建てられた絶景の木造テラスからは京都の素晴らしい眺めが広がり、国内でも特に重要な文化的宝の一つとなっています。<br><br>初めて京都を訪れる方や、一度のツアーで日本で最も有名で美しく歴史的な場所をまとめて発見したい方に最適な体験です。',

  'tour-kyoto-3h':
    '京都の伝統的で風情あふれる一面を、街を代表する路地や寺院を巡りながら発見しましょう。<br><br>まずは、京都の住民が日常的に訪れる憩いの場・鴨川沿いを歩き、この街ならではの雰囲気を感じます。続いて向かうのは、古都随一の美しさと写真映えを誇る祇園白川。石畳の路地、伝統的な木造の町家、柳が揺れる小川が並ぶこのエリアには、往時の日本の面影が今も息づいており、歴史ある花街の雰囲気を体感できます。<br><br>次に、日本で最も重要な仏教宗派の一つの本山である知恩院を訪問します。その威風堂々とした三門と広大な境内は、深い文化的・精神的な価値を秘めています。<br><br>その後、京都随一の名所として知られる円山公園を通り抜けます。四季折々の美しい景色と穏やかな雰囲気が魅力の場所です。<br><br>最後にたどり着くのは、ユネスコ世界遺産にも登録された清水寺。京都を一望できる有名な木造テラスは壮観の一言で、歴史・文化・伝統に満ちた旅のクライマックスにふさわしい場所です。<br><br>古都の古典的な美しさを発見し、日本の古都ならではの雰囲気に浸りたい方に最適な体験です。',

  'tour-himeji-3h':
    '日本で最も象徴的な都市の一つ、姫路の美しさと歴史を巡るツアーです。<br><br>姫路駅を出発し、お城へと続く優雅なメインストリート・大手前通りを歩きながら、街並みと地元の雰囲気を楽しみます。途中、地域を代表する食の名産品として知られるヤマサ蒲鉾にちなんだ伝統的な通りも通過します。<br><br>また、何世紀もの歴史を誇り、この地域の深い精神的伝統を体現する重要な信仰の場・播磨総社も訪問します。<br><br>ツアーのハイライトは、ユネスコ世界遺産に登録された姫路城。日本で最も保存状態の良い封建時代の城として知られ、その優美な外観から「白鷺城」とも呼ばれる、国内屈指の歴史的モニュメントです。<br><br>最後は姫路神社を訪れ、静かな雰囲気の中で地域の伝統や信仰についてさらに理解を深めます。<br><br>文化・建築・日本の遺産を組み合わせた、姫路の歴史的な本質を堪能したい方に最適なツアーです。🏯✨',

  'tour-nara-3h':
    '歴史、文化、伝統に満ちた旅で、日本の古都を発見しましょう。<br><br>スタート地点は近鉄奈良駅。国内でも最も歴史ある街を探索するための絶好の出発地です。歴史と自然美に囲まれた、奈良を代表する景観の一つ・猿沢池のほとりを散策します。<br><br>続いて、興福寺へ。街のシンボルとして知られる優美な五重塔を誇る、日本で最も重要な仏教寺院の一つです。日本の芸術と文化遺産についてさらに学べる奈良国立博物館も訪問した後、ユネスコ世界遺産に登録された東大寺へと向かいます。この壮大な複合施設には奈良の大仏が安置されており、世界最大級の青銅像として、日本の最も重要な文化的宝の一つとなっています。<br><br>ツアーを通じて、地元の伝統で神聖な使いとされる鹿が自由に闊歩する奈良公園の独特な雰囲気も楽しめます。<br><br>日本で最も魅力的な都市の一つが持つ、豊かな歴史的・精神的・文化的な深みを発見したい方に最適な体験です。🦌⛩️✨',

  'tour-nara-uji-8h':
    '歴史、精神性、そして伝統的な食文化が融合した旅で、日本で最も魅力的な2つの文化的目的地を訪れます。<br><br>最初に訪れるのは、国内最高品質の抹茶の産地として有名な宇治。ユネスコ世界遺産に登録された平等院鳳凰堂は、日本建築の傑作と称される名所です。その後、抹茶専門店や伝統的なお菓子、地域の茶文化を反映した名産品が並ぶ宇治の表参道を散策します。<br><br>続いて向かうのは、日本最初の恒久的首都・奈良。猿沢池のほとりを歩き、ユネスコ世界遺産にも登録された重要な仏教寺院・興福寺を訪問します。歴史ある五重塔でも知られるこの寺は、奈良の文化の核心を成しています。<br><br>また、訪問者と自由に共存する奈良を象徴する鹿たちが生息する奈良公園の散策も楽しみます。<br><br>ツアーのクライマックスは、ユネスコ世界遺産・東大寺。奈良の大仏は日本で最も印象的で象徴的な青銅像として広く知られています。<br><br>歴史的な寺院、何世紀にもわたる伝統、そして宇治の本物の抹茶の味を通じて、日本の文化的本質を知りたい方に最適な体験です。🍵🦌⛩️✨',

  'tour-himeji-kobe-8h':
    '関西地方で最も魅力的な2つの目的地を組み合わせたツアーです。<br><br>まず、ユネスコ世界遺産に登録された姫路城を訪問します。日本で最も保存状態の良い封建時代の城として知られ、「白鷺城」の名にふさわしい日本建築の傑作であり、国内でも特に印象的な歴史的モニュメントです。<br><br>姫路を巡った後は、コスモポリタンな雰囲気と国際的な歴史で知られる神戸・三宮へ移動します。神戸港に隣接するモダンなメリケンパークを散策しながら、美しい海の眺めと街を代表するシンボルを楽しみます。<br><br>昼食時には、この有名な日本の特産品を味わうための人気レストランの一つ、Steaklandで世界的に名高い神戸ビーフを堪能します。<br><br>午後は、かつての外国人商人や外交官が建てたエレガントな洋館が立ち並ぶ北野異人館街を散策。そしてツアーの締めくくりに、歴史と地元の商店、そして神戸を形作ってきた日本と国際的影響の独自の融合を反映した活気ある元町を訪れます。<br><br>歴史的遺産、海岸沿いの景色、国際文化、そして日本で最も名高い料理の一つを一日で満喫したい方に最適な体験です。🏯⚓🥩✨',

  'tour-osaka-presentation':
    '大阪が誇る活気ある都市の生活、美食、そして親しみやすい雰囲気を、この街のユニークなエネルギーとともに発見しましょう。<br><br>ツアーは最新のトレンドとローカル文化が交わる人気ショッピングエリア・心斎橋からスタートします。続いて向かうのは大阪のユースカルチャーの中心地・アメリカ村（アメ村）。クリエイティブな雰囲気、ストリートアート、個性派ブティック、そしてオルタナティブなスピリットで日本でも最もダイナミックな街の一つです。<br><br>次に到着するのは大阪の顔・道頓堀。巨大なネオンサイン、活気ある通り、そして唯一無二の雰囲気により、国内で最も写真に撮られるエリアの一つとなっています。<br><br>すぐ近くには、伝統的な大阪の風情を今に伝える静かな隠れ家・法善寺。賑やかな周辺の通りとの対比が魅力的です。<br><br>最後は「大阪の台所」として知られる黒門市場へ。地元の食材、新鮮な海の幸、和菓子、そして大阪を代表するグルメを発見できます。<br><br>文化、食、そして活気ある都市の生活を通じて大阪の真髄を体感したい方に最適な体験です。🍜✨🏮🇯🇵',

  'tour-osaka-3h':
    '大阪の鼓動を感じる旅。モダニティと伝統、そしてこの街を象徴するスポットを組み合わせたツアーです。<br><br>大阪で最も人気のあるショッピングエリアの一つ・心斎橋からスタート。店、カフェ、都市の活気に満ちた通りが、この街の最もダイナミックな側面を映し出します。<br><br>続いて向かうのは、アメリカ村。壁画、オルタナティブショップ、クリエイティブな雰囲気を持つこの街は、大阪の現代的で自由なスピリットを体現しています。<br><br>その後は大阪で最も有名な道頓堀へ。スペクタクルなネオン、活気ある雰囲気、そして地元のナイトライフとグルメの象徴として知られるこのエリアでは、日本で最もアイコニックな景色を楽しめます。<br><br>すぐ近くには、歴史的大阪の風情を今に伝える静かなオアシス・法善寺。周囲の喧騒とは対照的な穏やかなひとときを提供します。<br><br>ツアーの締めくくりは「大阪の台所」黒門市場。新鮮な食材、地元の名産品、そして日本料理を代表するフレーバーが揃う歴史ある市場です。<br><br>都市文化、伝統、そして名高いグルメシーンを通じて大阪の真髄を体感したい方に最適な体験です。',

  'tour-osaka-8h':
    '日本で最も活気あふれる都市の一つ、大阪の最も象徴的なスポットを歴史・文化・そのユニークなエネルギーとともに巡るツアーです。<br><br>まず訪れるのは大阪を代表するモニュメント・大阪城。広大な庭園と何世紀もの歴史を持つ城壁に囲まれたこの城は、日本の封建時代の歴史を感じる魅力的な場所です。<br><br>次に向かうのは大阪のエンターテインメントと都市の生活の中心・難波。活気ある通り、ショップ、レストランが立ち並ぶこのエリアは、大阪のダイナミックで親しみやすいキャラクターを体現しています。<br><br>その後は、20世紀初頭の大阪の雰囲気が今も残る懐かしい街・新世界を探索します。カラフルな看板、伝統的な通り、そして地元ならではの雰囲気が独自の体験を提供します。<br><br>さらに、大阪徒歩ツアーのハイライトスポットも訪れ、象徴的なランドマーク、歴史的な一角、そして街を代表するエリアを発見します。<br><br>歴史、文化、そして大阪ならではの都市エネルギーを通じて、この街の真髄を体感したい方に最適な体験です。',

  'tour-kobe-3h':
    '日本の伝統と国際的な影響が融合した魅力あふれる街、神戸を発見しましょう。<br><br>ツアーは神戸の中心地・三宮からスタート。この街を代表するスポットを巡るための絶好の出発地です。<br><br>最初に訪れるのは生田神社。1,800年以上の歴史を誇る日本最古の神社の一つで、都心の緑に囲まれたこの神社は、神戸の精神的な伝統への完璧な入口です。<br><br>次に向かうのは、神戸の国際的な過去を反映した歴史ある西洋風建物に入る北野異人館スターバックス。日本で最も美しいスターバックスの一つと称されるこの建物では、北野地区を特徴づける建築美を堪能できます。<br><br>さらに北野地区を散策し、神戸の最も認知されたシンボルの一つ・風見鶏の館へ。その独特な建築と歴史は、かつて外国人商人や外交官がこの地に移り住んだ時代を鮮やかに伝えています。<br><br>ツアーの途中には、日本で最も名高いグルメの一つ・神戸ビーフを味わうのに人気のSteaklandも通過します。<br><br>歴史、文化、そして神戸を日本で最も魅力的な都市の一つにしているコスモポリタンな雰囲気を発見したい方に最適な体験です。',

  'tour-kobe-8h':
    '歴史、国際的な建築、自然、そして壮大な海の景色を組み合わせた旅で、神戸の真髄を発見しましょう。<br><br>ツアーは神戸の中心地・三宮からスタート。この街を代表するランドマークを巡るための絶好の出発地です。<br><br>最初の目的地は生田神社。1,800年以上の歴史を誇る日本最古の神社の一つで、日本の伝統と信仰への魅力的な入口となっています。<br><br>続いて向かうのは、神戸の国際的な開港期に外国人商人や外交官が建てたエレガントな洋館が立ち並ぶ北野異人館街。歴史に彩られた通りと個性的な建築が、この街のコスモポリタンな特色を映し出します。<br><br>次に、市街地から程近い自然の名所・布引の滝を訪問。静かな景色の中でひと息つける、街の中の別世界です。<br><br>ツアーの途中には、世界的に名高い神戸ビーフを堪能するのに人気のSteaklandも通過します。<br><br>午後は神戸港に隣接するモダンなメリケンパークへ。湾の美しい眺め、開放的なウォーターフロント、そして街を代表するシンボルを楽しみます。<br><br>最後に向かうのは神戸ポートタワー。神戸で最も認知されたモニュメントの一つで、日本有数の港湾都市・神戸を形作った都市と海のランドスケープを堪能する絶好のスポットです。<br><br>歴史、自然、国際文化、そして海岸沿いの景色が融合したユニークな組み合わせで、神戸を忘れられない目的地にする特別な体験です。',
};

// ─────────────────────────────────────────────────────────────────────────────
// Apply
// ─────────────────────────────────────────────────────────────────────────────
const es = load('BdTours_es.json');
const en = load('BdTours_en.json');
const ja = load('BdTours_ja.json');

patch(es, ES);
patch(en, EN);
patch(ja, JA);

save('BdTours_es.json', es);
save('BdTours_en.json', en);
save('BdTours_ja.json', ja);

// Summary
const esPatch = Object.keys(ES).filter(id => es.find(t => t.id === id));
const enPatch = Object.keys(EN).filter(id => en.find(t => t.id === id));
const jaPatch = Object.keys(JA).filter(id => ja.find(t => t.id === id));
console.log(`✅ ES: ${esPatch.length} tours actualizados`);
console.log(`✅ EN: ${enPatch.length} tours actualizados`);
console.log(`✅ JA: ${jaPatch.length} tours actualizados`);
console.log('Tours ES:', esPatch.join(', '));
